datasources:
  default:
    url: jdbc:h2:mem:policyTestDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ""
---
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: false
---
kafka:
  embedded:
    enabled: true
---
tracing:
  zipkin:
    enabled: false
