apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service-legacy
  labels:
    app.kubernetes.io/name: policy-service-legacy
    app.kubernetes.io/instance: insurance-hub-policy-service-legacy
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: policy-service-legacy
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: policy-service-legacy
        app.kubernetes.io/instance: insurance-hub-policy-service-legacy
        app.kubernetes.io/version: "latest"
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: policy-service-legacy
          image: insurance-hub-policy-service-legacy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: policy-config-legacy
          env:
            - name: KUBERNETES_CLIENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MICRONAUT_SERVER_HOST
              value: "0.0.0.0"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3