apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: insurance-hub
      app.kubernetes.io/managed-by: kustomize
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: policy-config-legacy
    literals:
      - PG_HOST=localhost
      - PG_PORT=5432
      - PG_DBNAME=policy
      - PG_USER=policy
      - PG_PASSWORD=policy
      - PG_SSL=false
      - KAFKA_HOST=localhost
      - KAFKA_PORT=9092
      - TRACING_ZIPKIN_ENABLED=true
      - ZIPKIN_HOST=localhost
      - ZIPKIN_PORT=9411