apiVersion: v1
kind: Service
metadata:
  name: pricing-api-legacy
  labels:
    app.kubernetes.io/name: pricing-api-legacy
    app.kubernetes.io/instance: insurance-hub-pricing-api-legacy
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pricing-api-legacy
    app.kubernetes.io/component: api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP