apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: qa-data
  labels:
    strimzi.io/cluster: qa-kafka
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        class: local-path
        kraftMetadata: shared
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: qa-data
  labels:
    strimzi.io/cluster: qa-kafka
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        class: local-path
        kraftMetadata: shared
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: qa-kafka
spec:
  kafka:
    version: 4.1.0
    metadataVersion: 4.1-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # Multi node configuration
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      # Log retention
      log.retention.hours: 168
      log.segment.bytes: 1073741824
      log.retention.check.interval.ms: 300000
      log.cleanup.policy: delete
      log.cleaner.enable: true
      # Message compression
      compression.type: producer
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    metricsConfig:
      type: strimziMetricsReporter
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    userOperator:
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
---
apiVersion: v1
kind: Service
metadata:
  name: qa-kafka-metrics
  namespace: qa-data
  labels:
    strimzi.io/cluster: qa-kafka
spec:
  selector:
    strimzi.io/cluster: qa-kafka
  ports:
    - name: kafka-metrics
      port: 9404
      targetPort: 9404
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qa-kafka-metrics
  namespace: qa-data
  labels:
    release: qa-prometheus
spec:
  namespaceSelector:
    matchNames: ["qa-data"]
  selector:
    matchLabels:
      strimzi.io/cluster: qa-kafka
  endpoints:
    - port: kafka-metrics
      path: /metrics
      interval: 30s