apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa-svc
namePrefix: qa-
labels:
  - includeSelectors: true
    pairs:
      environment: qa
resources:
  - ../../../../../apps/svc/policy-search/base/legacy
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: policy-search-api-legacy
configMapGenerator:
  - name: policy-search-config-legacy
    behavior: merge
    literals:
      - ELASTIC_SCHEME=https
      - ELASTIC_HOST=qa-elasticsearch-es-http.qa-data.svc.cluster.local
      - ELASTIC_PORT=9200
      - KAFKA_HOST=qa-kafka-kafka-bootstrap.qa-data.svc.cluster.local
      - TRACING_ZIPKIN_ENABLED=true
      - ZIPKIN_HOST=qa-zipkin.qa-monitoring.svc.cluster.local