apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api-legacy
spec:
  template:
    spec:
      containers:
        - name: payment-api-legacy
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          env:
            # Postgres sensitive data
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-payment-user-creds
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-payment-user-creds
                  key: password
            # MinIO sensitive data
            - name: MINIO_SVC_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: qa-minio-payment-svc-user-creds
                  key: MINIO_SVC_ACCESS_KEY
            - name: MINIO_SVC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: qa-minio-payment-svc-user-creds
                  key: MINIO_SVC_SECRET_KEY