apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa-svc
namePrefix: qa-
labels:
  - includeSelectors: true
    pairs:
      environment: qa
resources:
  - ../../../../../apps/svc/payment/base/legacy
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: payment-api-legacy
configMapGenerator:
  - name: payment-config-legacy
    behavior: merge
    literals:
      - MINIO_TENANT_ENDPOINT=http://qa-minio-payment-hl.qa-minio-payment.svc.cluster.local:9000
      - PG_HOST=qa-postgres-payment-rw.qa-data.svc.cluster.local
      - KAFKA_HOST=qa-kafka-kafka-bootstrap.qa-data.svc.cluster.local
      - TRACING_ZIPKIN_ENABLED=true
      - ZIPKIN_HOST=qa-zipkin.qa-monitoring.svc.cluster.local
      - JSREPORT_HOST=qa-jsreport.qa-svc.svc.cluster.local