apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: payment
      owner: payment
      secret:
        name: local-dev-postgres-payment-user-creds
