apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: document
      owner: document
      secret:
        name: local-dev-postgres-document-creds
