micronaut:
  server:
    host: localhost
    port: 8084
---
kafka:
  bootstrap:
    servers: "localhost:9094"
---
tracing:
  zipkin:
    enabled: false
---
minio:
  tenant-endpoint: "http://localhost:9001"
---
jsreport:
  host: localhost
  port: 5488
---
postgres:
  host: localhost
  port: 5452
