apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa-svc
namePrefix: qa-
labels:
  - includeSelectors: true
    pairs:
      environment: qa
resources:
  - ../../../../../apps/svc/chat/base/legacy
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: chat-api-legacy
