apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: insurance-hub
      app.kubernetes.io/managed-by: kustomize
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: web-vue-config-legacy
    literals:
      - GATEWAY_URL=http://localhost:8090
      - AUTH_URL=http://localhost:8081
      - CHAT_URL=http://localhost:8082