apiVersion: v1
kind: Service
metadata:
  name: web-vue-legacy
  labels:
    app.kubernetes.io/name: web-vue-legacy
    app.kubernetes.io/instance: insurance-hub-web-vue-legacy
    app.kubernetes.io/component: web
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: web-vue-legacy
    app.kubernetes.io/component: web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP