apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa-minio-payment
namePrefix: qa-
resources:
  - ../../../../../apps/infra/minio/base
  - service-monitor.yaml
patches:
  - path: minio-payment-patch.yaml
    target:
      kind: Tenant
      name: minio-tenant
