apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: insurance-hub
      app.kubernetes.io/managed-by: kustomize
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: payment-config-legacy
    literals:
      - PAYMENTS_IMPORT_S3_BUCKET=payments-import
      - MINIO_TENANT_ENDPOINT=http://localhost:9000
      - PG_HOST=localhost
      - PG_PORT=5432
      - PG_DBNAME=payment
      - KAFKA_HOST=localhost
      - KAFKA_PORT=9092
      - TRACING_ZIPKIN_ENABLED=true
      - ZIPKIN_HOST=localhost
      - ZIPKIN_PORT=9411
      - JSREPORT_HOST=localhost
      - JSREPORT_PORT=5488