apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-dev-minio-document
namePrefix: local-dev-
nameSuffix: -document
resources:
  - ../../../../../apps/infra/minio/base
patches:
  - path: tenant-patch.yaml
    target:
      kind: Tenant
      name: minio
