micronaut:
  http:
    services:
      product-service:
        urls:
          - http://qa-product-api-legacy:80
      document-service:
        urls:
          - http://qa-document-api-legacy:80
      policy-search-service:
        urls:
          - http://qa-policy-search-api-legacy:80
