apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-dev-all
namePrefix: local-dev-
labels:
  - includeSelectors: true
    pairs:
      environment: local-dev
resources:
  - ../../../../../apps/svc/payment/base/legacy
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: payment-api-legacy
configMapGenerator:
  - name: payment-config-legacy
    behavior: merge
    literals:
      - MINIO_TENANT_ENDPOINT=http://local-dev-minio-payment-hl.local-dev-minio-payment.svc.cluster.local:9000
      - PG_HOST=local-dev-postgres-payment-rw.local-dev-all.svc.cluster.local
      - KAFKA_HOST=local-dev-kafka-kafka-bootstrap.local-dev-all.svc.cluster.local
      - TRACING_ZIPKIN_ENABLED=false
      - JSREPORT_HOST=local-dev-jsreport.local-dev-all.svc.cluster.local