apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-portal-gateway-legacy
  labels:
    environment: local-dev
spec:
  template:
    metadata:
      labels:
        environment: local-dev
    spec:
      containers:
        - name: agent-portal-gateway-legacy
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: "local-dev"
            - name: TRACING_ZIPKIN_ENABLED
              value: "false"
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m