micronaut:
  server:
    host: localhost
    port: 8089
---
kafka:
  bootstrap:
    servers: "localhost:9094"
---
tracing:
  zipkin:
    enabled: false
---
elastic:
  scheme: http
  host: localhost
  port: 9200
