apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: auth
      owner: auth
      secret:
        name: local-dev-postgres-auth-user-creds
