apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-api-legacy
spec:
  template:
    spec:
      containers:
        - name: document-api-legacy
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          env:
            # Postgres sensitive data
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-document-user-creds
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-document-user-creds
                  key: password
            # MinIO sensitive data
            - name: MINIO_SVC_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: qa-minio-document-svc-user-creds
                  key: MINIO_SVC_ACCESS_KEY
            - name: MINIO_SVC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: qa-minio-document-svc-user-creds
                  key: MINIO_SVC_SECRET_KEY