apiVersion: v1
kind: Service
metadata:
  name: auth-api-legacy
  labels:
    app.kubernetes.io/name: auth-api-legacy
    app.kubernetes.io/instance: insurance-hub-auth-api-legacy
    app.kubernetes.io/component: api
spec:
  type: NodePort # Should be exposed as NodePort given front-end communicates directly with it
  selector:
    app.kubernetes.io/name: auth-api-legacy
    app.kubernetes.io/component: api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP