apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: pricing
      owner: pricing
      secret:
        name: local-dev-postgres-pricing-user-creds
