apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -pricing
resources:
  - ../base
patches:
  - path: cluster-patch.yaml
    target:
      kind: Cluster
      name: postgres
