apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-legacy
spec:
  template:
    spec:
      containers:
        - name: auth-api-legacy
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          env:
            # Postgres sensitive data
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-auth-user-creds
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-auth-user-creds
                  key: password
