apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-legacy
spec:
  template:
    spec:
      containers:
        - name: auth-api-legacy
          env:
            - name: TRACING_ZIPKIN_ENABLED
              value: "true"
            - name: POSTGRES_HOST
              value: "qa-postgres-auth-rw.qa-data.svc.cluster.local"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"