apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-legacy
spec:
  template:
    spec:
      containers:
        - name: auth-api-legacy
          env:
            - name: TRACING_ZIPKIN_HTTP_URL
              value: http://qa-zipkin.qa-monitoring.svc.cluster.local:9411
            - name: POSTGRES_HOST
              value: qa-postgres-auth-rw.qa-data.svc.cluster.local
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-auth-user-creds
                  key: password
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
