apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa-svc
namePrefix: qa-
nameSuffix: -legacy
labels:
  - pairs:
      environment: qa
resources:
  - ../../../../apps/svc/agent-portal-gateway/base
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: agent-portal-gateway