apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-legacy
spec:
  template:
    spec:
      containers:
        - name: product-api-legacy
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          env:
            # MongoDB sensitive data
            - name: MG_USER
              valueFrom:
                secretKeyRef:
                  name: local-dev-mongodb-product-user-creds
                  key: username
            - name: MG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: local-dev-mongodb-product-user-creds
                  key: password
