apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-dev-all
namePrefix: local-dev-
labels:
  - includeSelectors: true
    pairs:
      environment: local-dev
resources:
  - ../../../../../apps/svc/product/base/legacy
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: product-api-legacy
configMapGenerator:
  - name: product-config-legacy
    behavior: merge
    literals:
      - MG_HOST=local-dev-mongodb-svc.local-dev-all.svc.cluster.local
      - MG_PORT=27017
      - TRACING_ZIPKIN_ENABLED=false