apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-search-api-legacy
spec:
  template:
    spec:
      containers:
        - name: policy-search-api-legacy
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          env:
            # Elasticsearch sensitive data
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: local-dev-elasticsearch-es-elastic-user
                  key: elastic