apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-search-api-legacy
spec:
  template:
    spec:
      containers:
        - name: policy-search-api-legacy
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          env:
            # Elasticsearch sensitive data
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: local-dev-elasticsearch-es-elastic-user
                  key: elastic