apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-portal-gateway-legacy
  labels:
    environment: qa
spec:
  template:
    metadata:
      labels:
        environment: qa
    spec:
      containers:
        - name: agent-portal-gateway-legacy
          env:
            - name: TRACING_ZIPKIN_HTTP_URL
              value: "http://qa-zipkin.qa-monitoring.svc.cluster.local:9411"
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m