apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-portal-gateway-legacy
  labels:
    environment: qa
spec:
  template:
    metadata:
      labels:
        environment: qa
    spec:
      containers:
        - name: agent-portal-gateway-legacy
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 300m
              memory: 768Mi
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: "qa"
            - name: TRACING_ZIPKIN_HTTP_URL
              value: "http://qa-zipkin.qa-monitoring.svc.cluster.local:9411"
