apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa-data
namePrefix: qa-
resources:
  - ../../../../../apps/infra/postgres/base
patches:
  - path: cluster-patch.yaml
    target:
      kind: Cluster
      name: postgres
