apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-api-legacy
spec:
  template:
    spec:
      containers:
        - name: pricing-api-legacy
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: "qa"
            # Postgres sensitive data
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-pricing-user-creds
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-pricing-user-creds
                  key: password