apiVersion: v1
kind: Service
metadata:
  name: agent-portal-gateway-legacy
  labels:
    app.kubernetes.io/name: agent-portal-gateway-legacy
    app.kubernetes.io/instance: insurance-hub-agent-portal-gateway-legacy
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: agent-portal-gateway-legacy
    app.kubernetes.io/component: gateway
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP