apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service-legacy
spec:
  template:
    spec:
      containers:
        - name: policy-service-legacy
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
          env:
            # Postgres sensitive data
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-policy-user-creds
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: qa-postgres-policy-user-creds
                  key: password