micronaut:
  application:
    name: product-service
  server:
    host: localhost
    port: 8080
#  metrics:
#    enabled: true
---
jackson:
  bean-introspection-module: true
---
mongodb:
    uri: "mongodb://${MG_USER:product}:${MG_PASSWORD:product}@${MG_HOST:localhost}:${MG_PORT:27017}/products-demo"
    cluster:
      maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
---
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
#  metrics:
#    enabled: true
#    sensitive: false
---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.

