apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  bootstrap:
    initdb:
      database: product
      owner: product
      secret:
        name: local-dev-postgres-product-creds
