apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-dev-all
namePrefix: local-dev-
nameSuffix: -product
resources:
  - ../../../../../apps/infra/postgres/base
patches:
  - path: cluster-patch.yaml
    target:
      kind: Cluster
      name: postgres
