apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-dev-minio-payment
namePrefix: local-dev-
resources:
  - ../../../../../apps/infra/minio/base
patches:
  - path: minio-payment-patch.yaml
    target:
      kind: Tenant
      name: minio-tenant
