micronaut:
  server:
    host: localhost
    port: 8087
---
endpoints:
  env:
    enabled: true
    sensitive: false
---
tracing:
  zipkin:
    enabled: false
---
postgres:
  host: localhost
  port: 5482
