apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-legacy
spec:
  template:
    spec:
      containers:
        - name: auth-api-legacy
          env:
            - name: TRACING_ZIPKIN_ENABLED
              value: "false"
            - name: POSTGRES_HOST
              value: "local-dev-postgres-auth-rw.local-dev-all.svc.cluster.local"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"