apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-dev-all
namePrefix: local-dev-

labels:
  - includeSelectors: true
    pairs:
      environment: local-dev

resources:
  - ../../../../../apps/svc/auth/base/legacy

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: auth-api-legacy