replicaCount: 1
image:
  repository: openzipkin/zipkin
  tag: 3.5.1
  pullPolicy: IfNotPresent
zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: "http://qa-elasticsearch-es-http.qa-data.svc.cluster.local:9200"
      # Authentication credentials populated from Kubernetes secret
      # These values will be overridden by environment variables from the secret through Helm
      username: ""
      password: ""
      index: zipkin
service:
  type: ClusterIP
  port: 9411
resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"
# PVC Persistence disabled because storage is Elasticsearch
persistence:
  enabled: false
serviceMonitor:
  enabled: false
extraEnvFrom:
  - secretRef:
      name: qa-zipkin-es-user-creds
