apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa-svc
namePrefix: qa-
labels:
  - includeSelectors: true
    pairs:
      environment: qa
resources:
  - ../../../../../apps/svc/product/base/legacy
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: product-api-legacy
configMapGenerator:
  - name: product-config-legacy
    behavior: merge
    literals:
      - MG_HOST=qa-mongodb-svc.qa-data.svc.cluster.local
      - MG_PORT=27017
      - TRACING_ZIPKIN_ENABLED=true