apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qa-svc
namePrefix: qa-
labels:
  - includeSelectors: true
    pairs:
      environment: qa
resources:
  - ../../../../../apps/svc/web-vue/base/legacy
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: web-vue-legacy
configMapGenerator:
  - name: web-vue-config-legacy
    behavior: merge
    literals:
      - GATEWAY_URL=http://qa-agent-portal-gateway-legacy.qa-svc.svc.cluster.local
      - AUTH_URL=http://qa-auth-api-legacy.qa-svc.svc.cluster.local
      - CHAT_URL=http://qa-chat-api-legacy.qa-svc.svc.cluster.local