apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa-minio-document
namePrefix: qa-
nameSuffix: -document
resources:
  - ../../../../../apps/infra/minio/base
  - service-monitor.yaml
patches:
  - path: tenant-patch.yaml
    target:
      kind: Tenant
      name: minio
