apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-dev-all
namePrefix: local-dev-
labels:
  - includeSelectors: true
    pairs:
      environment: local-dev
resources:
  - ../../../../../apps/svc/policy/base/legacy
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: policy-api-legacy
configMapGenerator:
  - name: policy-config-legacy
    behavior: merge
    literals:
      - PG_HOST=local-dev-postgres-policy-rw.local-dev-all.svc.cluster.local
      - KAFKA_HOST=local-dev-kafka-kafka-bootstrap.local-dev-all.svc.cluster.local
      - TRACING_ZIPKIN_ENABLED=false
